### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by XrsSjtu** [Ethanscuter/SimPGAN#1]
Hi,I download the grid and market data in grid and market directory.When i run the code, i meet the following problem which is very confuse to me.Have you ever meet this problem before,thanks. 

Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 31, in main
    solver.train()
  File "/tmp/ReidDataSet/ReidCode/SimPGAN/solver.py", line 181, in train
    market, m_labels = market_iter.next()
ValueError: too many values to unpack

**Comment by Ethanscuter** [comment]
Hi, thx for your interest in my work. It seems that the problem lies in python language Tuple Unpack. U can try to go through the function market_iter. Maybe python version causes this problem.
