### ISSUE TITLE
End-to-End method?

### ISSUE THREAD

**Issue by deep0learning** [Ethanscuter/SimPGAN#2]
Hi is it an end to end method? Or you generate images in one phase then you apply the generated imaged in another phase in the reID system?

**Comment by Ethanscuter** [comment]
Yes, it is an end to end system

**Comment by deep0learning** [comment]
Can you add some instruction on how I can reproduce your results?

**Comment by Ethanscuter** [comment]
Hi, sorry for the missing instructions, because this work was done one and a half year ago. 
1. Data, you should place your own data in the files like grid and market. No need to worry about the size because I resize all the pics before training.
2. Pre-train, pre-train.py is an identification model and pretrain_siamese.py is a siamese model which is based on the identification model. You should pretrain these models before running the gan code.
3. main.py is the place you revise the prameters.
4. model_gan.py model Reid.py are some code about gan and Reid. Notice, I rewrite most of the cyclegan code to make it simpler to follow and revise.
4. solver.py and related files are key code in the project, which controls how to build the net and optimize the nets.

**Comment by Ethanscuter** [comment]
If you have any other questions, it may the setting or framework problem, like the version of pytorch. Feel free to contact me.

**Comment by deep0learning** [comment]
Hi,
Thank you so much. I run pre-train.py  and 2\. pretrain_siamese.py sucessfully. Then I also run main.py and it generate 2 images in the samples folder. 

Then I got the following error.

Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 31, in main
    solver.train()
  File "/home/dlm/End-to-End/SimPGAN-master/solver_siamese.py", line 449, in train
    scipy.misc.imsave(path, grid_transfer)
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 219, in imsave
    im.save(name)
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 1932, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './samples/probe/0001_1_25004_107_32_106_221.jpeg'

After running the main.py, it will create three folders in samples folder?

**Comment by Ethanscuter** [comment]
Great! 
I am not sure whether it is automatic to create files and save images.  These images are used to compute Rank scores in the evaluation codes. If you have any questions, just look through the evaluation codes.

**Comment by mahfuj9346449** [comment]
@Ethanscuter If you do not use the generated images for re-id, how you can call it is an end-to-end method? You should be careful about the code,

**Comment by Ethanscuter** [comment]
@mahfuj9346449 I am quite confused about your criticize. I helped the user @deep0learning to run this code, and then you ask me to be careful about the code. His question is about how to use images in the sample folders to compute rank scores. Please make the Reid problems clear before you make any comments about other people's work. Like most of the work, the evaluating process uses the generated images to compute rank scores. The training process follows the end to end way.

**Comment by mahfuj9346449** [comment]
@Ethanscuter Thank you. I think the user @deep0learning asked to where you have used the generated images to train re-id model. I also run this code but it saves only two images in the samples folder. The code interprets that you have calculated re-id accuracy by using the gallery, probe and train images, my question is how you use the generated images in re-id?
