### ISSUE TITLE
Error in Pretrain.py

### ISSUE THREAD

**Issue by amena6490** [Ethanscuter/SimPGAN#5]
Hi, thank you for the nice work. I got the following error when running "pretrain.py".  How can I solve this issue?

/home/redhat/cd/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
Traceback (most recent call last):
  File "pretrain.py", line 188, in <module>
    softmax_pretrain_on_datasets(source)
  File "pretrain.py", line 182, in softmax_pretrain_on_datasets
    softmax_model_pretrain(train_list, train_dir, class_count, './' + source + '_softmax_pretrain.pkl')
  File "pretrain.py", line 146, in softmax_model_pretrain
    out_nouse, outputs = model(images)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 73, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 83, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "pretrain.py", line 106, in forward
    out = self.fc(x)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/redhat/cd/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
**RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1523244252089/work/torch/lib/THC/generic/THCTensorMathBlas.cu:247**

**Comment by Ethanscuter** [comment]
Because your GPU capacity is not enough to hold this minibatch. Try to set minibatch smaller or use a GPU whose capacity is more than 10G.
